workflows:
  version: 2
  # Staging deployment
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - manual_lock
            # - build
          filters:
            branches:
              only: develop
      # testing manual approval
      - manual_lock: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
            - build
          # filters:
          #   branches:
          #     only: master
      - deploy-prod:
          requires:
            - manual_lock
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
        # https://crontab.guru/
        # Time is UTC
        cron: '2 * * * *'
        filters:
          branches:
            only:
              - develop
    jobs:
      - build

version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # >> https://hub.docker.com/r/circleci/ruby/
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          # https://circleci.com/docs/2.0/databases/
          DATABASE_TEST_URL: postgresql://root@localhost/circle_test
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.5-alpine-ram
    working_directory: ~/repo

    steps:
      - checkout

      # === Dependencies ===
      # Download and cache dependencies
      - restore_cache:
          keys:
            - learnzone-aws-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - learnzone-aws-dependencies-
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: learnzone-aws-dependencies-{{ checksum "Gemfile.lock" }}

  deploy-dev:
    docker:
      - image: circleci/python:3.7.2-stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to AWS EB (Dev)
          command: eb deploy learnzone-aws-dev --profile eb-cli --label learnzone-aws-dev-$CIRCLE_BUILD_NUM

  deploy-prod:
    docker:
      - image: circleci/python:3.7.2-stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to AWS EB (Prod)
          command: eb deploy learnzone-aws --profile eb-cli --label learnzone-aws-$CIRCLE_BUILD_NUM
